name: fox_fit
description: App for trainers in gym.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.5+22

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  mask_text_input_formatter: ^2.0.0
  get: ^4.6.1
  dio: ^4.0.4
  flutter_svg: ^1.0.3
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.18
  swipe: ^0.0.1
  shared_preferences: ^2.0.12
  rive: ^0.8.1
  flutter_vibrate: ^1.3.0
  connectivity_plus: ^2.2.0
  flutter_local_notifications: ^9.2.0
  simple_gesture_detector: ^0.2.0
  characters: ^1.2.0
  package_info_plus: ^1.4.2
  flutter_config: ^2.0.0
  webview_flutter: ^3.0.4

  get_it: ^7.2.0
  injectable: ^1.5.3
  push_service_interface:
    path: packages/interface/push_service_interface
    
# GMS
  push_service:
    path: packages/gms/push_service

# HMS
  # push_service:
  #   path: packages/hms/push_service
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/


  fonts:
    - family: Open Sans
      fonts:
        - asset: lib/assets/font/OpenSans-Regular.ttf
        - asset: lib/assets/font/OpenSans-Bold.ttf
        - asset: lib/assets/font/OpenSans-BoldItalic.ttf
        - asset: lib/assets/font/OpenSans-ExtraBold.ttf
        - asset: lib/assets/font/OpenSans-ExtraBoldItalic.ttf
        - asset: lib/assets/font/OpenSans-Italic.ttf
        - asset: lib/assets/font/OpenSans-Light.ttf
        - asset: lib/assets/font/OpenSans-LightItalic.ttf
        - asset: lib/assets/font/OpenSans-Medium.ttf
        - asset: lib/assets/font/OpenSans-MediumItalic.ttf
        - asset: lib/assets/font/OpenSans-SemiBold.ttf
        - asset: lib/assets/font/OpenSans-SemiBoldItalic.ttf
    - family: Roboto
      fonts:
        - asset: lib/assets/font/Roboto-Black.ttf
        - asset: lib/assets/font/Roboto-Bold.ttf
        - asset: lib/assets/font/Roboto-Medium.ttf
        - asset: lib/assets/font/Roboto-Regular.ttf
        - asset: lib/assets/font/Roboto-Thin.ttf
       
flutter_intl:
  enabled: true
